// Warning: Some assembly references could not be resolved automatically. This might lead to incorrect decompilation of some parts,
// for ex. property getter/setter access. To get optimal decompilation results, please manually add the missing references to the list of loaded assemblies.

// E:\VirtualTexturesEditor\GrBuild.exe
// GrBuild, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null
// Global type: <Module>
// Entry point: GrBuild.Program.Main
// Architecture: x64
// Runtime: v4.0.30319
// Hash algorithm: SHA1

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Text.RegularExpressions;
using Graphine.Core;
using GrBuildLib;
using GrBuildLib.Tools;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: AssemblyCompany("Graphine NV")]
[assembly: AssemblyProduct("Tile Set Builder")]
[assembly: AssemblyCopyright("Copyright Graphine NV © 2013-2017")]
[assembly: AssemblyInformationalVersion("5.0.7.34144")]
[assembly: AssemblyDescription("Generated by cholleme@ZELDA from master/9a8e2032016ca90aea9bc098289abc7dc1f56d8c")]
[assembly: AssemblyTitle("GrBuild")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: Guid("74fb1abe-bba0-4e42-b67a-903def907785")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: TargetFramework(".NETFramework,Version=v4.5", FrameworkDisplayName = ".NET Framework 4.5")]
[assembly: AssemblyVersion("1.5.0.0")]
namespace GrBuild
{
	public class AssemblyHelper
	{
		public static string AssemblyTitle
		{
			get
			{
				object[] customAttributes = Assembly.GetExecutingAssembly().GetCustomAttributes(typeof(AssemblyTitleAttribute), inherit: false);
				if (customAttributes.Length != 0)
				{
					AssemblyTitleAttribute assemblyTitleAttribute = (AssemblyTitleAttribute)customAttributes[0];
					if (assemblyTitleAttribute.Title != "")
					{
						return assemblyTitleAttribute.Title;
					}
				}
				return Path.GetFileNameWithoutExtension(Assembly.GetExecutingAssembly().CodeBase);
			}
		}

		public static string AssemblyInformationalVersion
		{
			get
			{
				object[] customAttributes = Assembly.GetExecutingAssembly().GetCustomAttributes(typeof(AssemblyInformationalVersionAttribute), inherit: false);
				if (customAttributes.Length == 0)
				{
					return "";
				}
				return ((AssemblyInformationalVersionAttribute)customAttributes[0]).InformationalVersion;
			}
		}

		public static string AssemblyDescription
		{
			get
			{
				object[] customAttributes = Assembly.GetExecutingAssembly().GetCustomAttributes(typeof(AssemblyDescriptionAttribute), inherit: false);
				if (customAttributes.Length == 0)
				{
					return "";
				}
				return ((AssemblyDescriptionAttribute)customAttributes[0]).Description;
			}
		}

		public static string AssemblyProduct
		{
			get
			{
				object[] customAttributes = Assembly.GetExecutingAssembly().GetCustomAttributes(typeof(AssemblyProductAttribute), inherit: false);
				if (customAttributes.Length == 0)
				{
					return "";
				}
				return ((AssemblyProductAttribute)customAttributes[0]).Product;
			}
		}

		public static string AssemblyCopyright
		{
			get
			{
				object[] customAttributes = Assembly.GetExecutingAssembly().GetCustomAttributes(typeof(AssemblyCopyrightAttribute), inherit: false);
				if (customAttributes.Length == 0)
				{
					return "";
				}
				return ((AssemblyCopyrightAttribute)customAttributes[0]).Copyright;
			}
		}

		public static string AssemblyCompany
		{
			get
			{
				object[] customAttributes = Assembly.GetExecutingAssembly().GetCustomAttributes(typeof(AssemblyCompanyAttribute), inherit: false);
				if (customAttributes.Length == 0)
				{
					return "";
				}
				return ((AssemblyCompanyAttribute)customAttributes[0]).Company;
			}
		}
	}
	[Obfuscation(Exclude = true, ApplyToMembers = true)]
	internal class CommandLineOptions
	{
		[CommandLineParameter(Name = "project", RequiredSequential = true)]
		public string projectPath;

		[CommandLineParameter(Name = "new", ShortName = "n", Description = "(-n) Specify if a new project file should be created \n\n\tExample: GrBuild.exe MyProject.gproj -n")]
		public bool newProject;

		[CommandLineParameter(Name = "verbosity", ShortName = "v", ValueName = "<level>", Description = "(-v) Display this amount of information in the event log.\n\tThe available verbosity levels are:\n\tq[uiet], n[ormal], d[etailed]\n\n\tExample: --verbosity q or -v q")]
		public string verbosity;

		[CommandLineParameter(Name = "nofilelogger", ShortName = "nolog", Description = "(-nolog) Disable logging build output to a file.\n\tBy default the build output is logged to the file ProjectName.log.")]
		public bool noLog;

		public bool validate;

		[CommandLineParameter(Name = "delete", ShortName = "del", ValueName = "<assset name>", Description = "(-del) Delete an asset given the asset name.\n\tUse \"all\" to delete all assets (-del all)\n\tExample: --delete MyAsset or -del MyAsset")]
		public string assetToDelete;

		[CommandLineParameter(Name = "task", ShortName = "t", ValueName = "<task name>", Description = "(-task) Execute a build task. The available tasks are:\n\tbuild(default - build gts)\n\trebuild (clean intermediate files first then build)\n\tclean (only clean intermediate files if any found).\n\tnobuild (don't build, only run necessary processes for import/delete)\n\n\tExample: --task rebuild or -t rebuild")]
		public string task;

		[CommandLineParameter(Name = "importassets", ShortName = "i", ValueName = "<path>", Description = "(-i) Import all assets described in <file>.\n\n\tExample: --importassets myassets.xml or -i myassets.xml")]
		public string importAssetsPath;

		[CommandLineParameter(Name = "exclusive", ShortName = "e", Description = "(-e) Specifiy that the import is exclusive.\n\tExisting assets in the project that are not part of the xml file will be removed.\n\tThis option only works in combination with the importassets option\n\n\tExample: --importassets assets.xml --exclusive or -i assets.xml -e")]
		public bool exclusiveImport;

		[CommandLineParameter(Name = "config", ShortName = "c", ValueName = "<config name>", Description = "(-c) Set the configuration to use. Configurations are:\n\tfast (default), optimized.\n\tNote that intermediary files in the build process are written to\n\tthe config subfolder in the intermediary directory, e.g., './tmp/fast/pages.dat'\n\n\tExample: --config fast or -c fast", Hidden = true)]
		public string config;

		[CommandLineParameter(Name = "options", ShortName = "opt", ValueName = "name:value,name:value", Atomic = false, Description = "(-opt) Set extra options. See manual for extra options. \n\n\tExample: -opt \"Tilingmode:Hardware,MaximumAnisotropy:8,Pagesize:65536\"")]
		public string options;

		[CommandLineParameter(Name = "output", ShortName = "o", ValueName = "<path>", Atomic = false, Description = "(-o) Set output file path\n\n\tExample: -o \"OutputFile.gts\"")]
		public string outputPath;

		[CommandLineParameter(Name = "pagesdir", ShortName = "p", ValueName = "<relative path>", Atomic = false, Description = "(-p) Set relative directory for storing the page files, start path with directory name. \n\tExample: -p \"pages\" or --pagesdir \"somedir/otherdir\"")]
		public string pagesDirectory;

		[CommandLineParameter(Name = "gtexdir", ShortName = "g", ValueName = "<relative path>", Atomic = false, Description = "(-g) Set relative directory for storing the gtex files, start path with directory name. \n\tExample: -g \"GTEXFiles\" or --gtexdir \"somedir/otherdir\"")]
		public string soupDirectory;

		[CommandLineParameter(Name = "buildprofile", ShortName = "pr", ValueName = "<profile name>", Atomic = false, Description = "(-pr) Set Build Profile to one of the available built-in profiles, set by name. \n\tExample: -pr \"Default\" or --profile \"Default\"")]
		public string profile;

		[CommandLineParameter(Name = "version", ShortName = "version", Atomic = true, Description = "(-version) Display version information only.")]
		public bool showVersion;

		[CommandLineParameter(Name = "help", ShortName = "h", Atomic = true, Description = "(-h) Display this use message.")]
		public bool showHelp;

		[CommandLineParameter(Name = "warninglevel", ShortName = "w", Atomic = false, Description = "(-w) Set Warning Level between 1 and 3. See manual for summary of warning level conditions\n\nExample: -w 2")]
		public string warningLevel;

		[CommandLineParameter(Name = "nopatching", ShortName = "np", Atomic = false, Description = "(-np) Prevent GTex and GTS patching, never builds the GTS and GTex incrementally.")]
		public bool nopatching;

		[CommandLineParameter(Name = "nouniformcoding", ShortName = "nuu", Atomic = false, Description = "(-nuu) Disable the use of special coding of uniform areas in a GTS (set to enable compatibility with older runtimes not supporing uniform coding).")]
		public bool disableUniformCoding;

		[CommandLineParameter(Name = "profiling", ShortName = "pro", Atomic = false, Description = "(-pro) Enable profiling.", Hidden = true)]
		public bool profiling;

		[CommandLineParameter(Name = "strict", ShortName = "str", Atomic = false, Description = "(-str) Enable strict mode. Strict mode prevents certain features which can have unexpected side effects, such as automatic resizing of assets with changing aspect ratio, bit depth conversion, etc.")]
		public bool enableStrictMode;

		[CommandLineParameter(Name = "lightmapmode", ShortName = "lightmapmode", Atomic = false, Description = "Undocumented", Hidden = false)]
		public bool lightmapmode;

		[CommandLineParameter(Name = "cleanincludegtex", ShortName = "cleanincludegtex", Atomic = false, Description = "When cleaning (-t clean) also cleans the GTEX files.", Hidden = false)]
		public bool cleanIncludeGTex;

		[CommandLineParameter(Name = "cleanincludetileset", ShortName = "cleanincludetileset", Atomic = false, Description = "When cleaning (-t clean) also cleans the tile set files (.gts and .gtp files).", Hidden = false)]
		public bool cleanIncludeTileset;

		[CommandLineParameter(Name = "forceusegtex", ShortName = "forceusegtex", Atomic = false, Description = "Force using existing GTex files, even if the GTex files are out dated.", Hidden = false)]
		public bool forceUseGTex;

		[CommandLineParameter(Name = "allowforeigngtex", ShortName = "allowforeigngtex", Atomic = false, Description = "Allow the use of GTex files built by another project (use together with the 'forceusegtex' flag).", Hidden = false)]
		public bool allowForeignGTex;

		[CommandLineParameter(Name = "buildnotileset", ShortName = "buildnotileset", Atomic = false, Description = "No GTS file is written by the tools. The build process ends after GTex files are created.", Hidden = false)]
		public bool omitGTS;

		[CommandLineParameter(Name = "noredirection", ShortName = "noredirection", Atomic = false, Description = "Disable redirection of tiles in the GTS.", Hidden = false)]
		public bool noRedirection;

		[CommandLineParameter(Name = "nosharedmiptiles", ShortName = "nosharedmiptiles", Atomic = false, Description = "Disable shared mip tile generation when building the GTS.", Hidden = false)]
		public bool noSharedMipTiles;

		[CommandLineParameter(Name = "nomipstripping", ShortName = "nomipstripping", Atomic = false, Description = "Disable embedded mip stripping where a tile's mip if it resides in the same page as the tile, is only coded once", Hidden = false)]
		public bool noMipStripping;

		[CommandLineParameter(Name = "setguid", ShortName = "setguid", Atomic = false, Description = "Set the GUID of the active project. Example: -forceguid \"{0f8fad5b-d9cb-469f-a165-70867728950e}\"", Hidden = true)]
		public string setGuid;

		[CommandLineParameter(Name = "buildgtsforgtex", ShortName = "buildgtsforgtex", Atomic = false, Description = "Build a GTS file stripping where a tile's mip if it resides in the same page as the tile, is only coded once", Hidden = false)]
		public bool buildGTSforGTex;
	}
	[Obfuscation(Exclude = true, ApplyToMembers = true)]
	public class CommandLineParser
	{
		private readonly object _optionsObject;

		private readonly Queue<MemberInfo> _requiredOptions = new Queue<MemberInfo>();

		private readonly Dictionary<string, MemberInfo> _optionalOptions = new Dictionary<string, MemberInfo>();

		private readonly Dictionary<string, MemberInfo> _shortOptions = new Dictionary<string, MemberInfo>();

		private readonly Dictionary<string, MemberInfo> _atomicOptions = new Dictionary<string, MemberInfo>();

		private readonly Dictionary<string, MemberInfo> _atomicShortOptions = new Dictionary<string, MemberInfo>();

		private readonly List<string> _requiredUsageHelp = new List<string>();

		public string Title { get; set; }

		public CommandLineParser(object optionsObject)
		{
			_optionsObject = optionsObject;
			FieldInfo[] fields = optionsObject.GetType().GetFields();
			foreach (FieldInfo fieldInfo in fields)
			{
				CommandLineParameterAttribute attribute = GetAttribute<CommandLineParameterAttribute>(fieldInfo);
				if (attribute == null)
				{
					continue;
				}
				if (attribute.RequiredSequential)
				{
					_requiredOptions.Enqueue(fieldInfo);
					_requiredUsageHelp.Add($"<{attribute.Name}>");
				}
				else if (attribute.Atomic)
				{
					_atomicOptions.Add(attribute.Name.ToLowerInvariant(), fieldInfo);
					if (!string.IsNullOrEmpty(attribute.ShortName))
					{
						_atomicShortOptions.Add(attribute.ShortName.ToLowerInvariant(), fieldInfo);
					}
				}
				else
				{
					_optionalOptions.Add(attribute.Name.ToLowerInvariant(), fieldInfo);
					if (!string.IsNullOrEmpty(attribute.ShortName))
					{
						_shortOptions.Add(attribute.ShortName.ToLowerInvariant(), fieldInfo);
					}
				}
			}
			MethodInfo[] methods = optionsObject.GetType().GetMethods();
			foreach (MethodInfo methodInfo in methods)
			{
				CommandLineParameterAttribute attribute2 = GetAttribute<CommandLineParameterAttribute>(methodInfo);
				if (attribute2 == null)
				{
					continue;
				}
				if (methodInfo.GetParameters().Length > 1)
				{
					throw new NotSupportedException("Methods must have one or zero parameters.");
				}
				if (attribute2.RequiredSequential)
				{
					_requiredOptions.Enqueue(methodInfo);
					_requiredUsageHelp.Add($"<{attribute2.Name}>");
				}
				else if (attribute2.Atomic)
				{
					_atomicOptions.Add(attribute2.Name.ToLowerInvariant(), methodInfo);
					if (!string.IsNullOrEmpty(attribute2.ShortName))
					{
						_atomicShortOptions.Add(attribute2.ShortName.ToLowerInvariant(), methodInfo);
					}
				}
				else
				{
					_optionalOptions.Add(attribute2.Name.ToLowerInvariant(), methodInfo);
					if (!string.IsNullOrEmpty(attribute2.ShortName))
					{
						_shortOptions.Add(attribute2.ShortName.ToLowerInvariant(), methodInfo);
					}
				}
			}
		}

		public bool ParseCommandLine(string[] args)
		{
			bool result = true;
			for (int i = 0; i < args.Length; i++)
			{
				if (args[i].StartsWith("-"))
				{
					string text = args[i];
					string value = "true";
					if (i + 1 < args.Length && !args[i + 1].StartsWith("-"))
					{
						value = args[i + 1];
						i++;
					}
					MemberInfo value2;
					if (text.StartsWith("--"))
					{
						text = text.Substring(2);
						if (_atomicOptions.TryGetValue(text.ToLowerInvariant(), out value2))
						{
							return SetOption(value2, value);
						}
						if (!_optionalOptions.TryGetValue(text.ToLowerInvariant(), out value2))
						{
							ShowError("Unknown option '{0}'", text);
							return false;
						}
					}
					else
					{
						text = text.Substring(1);
						if (_atomicShortOptions.TryGetValue(text.ToLowerInvariant(), out value2))
						{
							return SetOption(value2, value);
						}
						if (!_shortOptions.TryGetValue(text.ToLowerInvariant(), out value2))
						{
							ShowError("Unknown option '{0}'", text);
							return false;
						}
					}
					if (!SetOption(value2, value))
					{
						return false;
					}
				}
				else
				{
					if (_requiredOptions.Count <= 0)
					{
						ShowError("Too many arguments");
						return false;
					}
					MemberInfo memberInfo = _requiredOptions.Peek();
					if (!IsList(memberInfo))
					{
						_requiredOptions.Dequeue();
					}
					SetOption(memberInfo, args[i]);
				}
			}
			MemberInfo memberInfo2 = _requiredOptions.FirstOrDefault((MemberInfo field) => !IsList(field) || GetList(field).Count == 0);
			if (memberInfo2 != null)
			{
				ShowError("Missing argument '{0}'", GetAttribute<CommandLineParameterAttribute>(memberInfo2).Name);
				return false;
			}
			return result;
		}

		private bool SetOption(MemberInfo member, string value)
		{
			try
			{
				if (IsList(member))
				{
					GetList(member).Add(ChangeType(value, ListElementType(member as FieldInfo)));
				}
				else if (member is MethodInfo)
				{
					MethodInfo methodInfo = member as MethodInfo;
					ParameterInfo[] parameters = methodInfo.GetParameters();
					if (parameters.Length == 0)
					{
						methodInfo.Invoke(_optionsObject, null);
					}
					else
					{
						methodInfo.Invoke(_optionsObject, new object[1] { ChangeType(value, parameters[0].ParameterType) });
					}
				}
				else
				{
					FieldInfo fieldInfo = member as FieldInfo;
					fieldInfo.SetValue(_optionsObject, ChangeType(value, fieldInfo.FieldType));
				}
				return true;
			}
			catch
			{
				ShowError("Invalid value '{0}' for option '{1}'", value, GetAttribute<CommandLineParameterAttribute>(member).Name);
				return false;
			}
		}

		private static object ChangeType(string value, Type type)
		{
			return TypeDescriptor.GetConverter(type).ConvertFromInvariantString(value);
		}

		private static bool IsList(MemberInfo field)
		{
			if (field is MethodInfo)
			{
				return false;
			}
			return typeof(IList).IsAssignableFrom((field as FieldInfo).FieldType);
		}

		private IList GetList(MemberInfo field)
		{
			return (IList)(field as FieldInfo).GetValue(_optionsObject);
		}

		private static Type ListElementType(FieldInfo field)
		{
			return (from i in field.FieldType.GetInterfaces()
				where i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>)
				select i).First().GetGenericArguments()[0];
		}

		public void ShowUsage()
		{
			ShowError(null);
		}

		public void ShowError(string message, params object[] args)
		{
			string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(Process.GetCurrentProcess().ProcessName);
			if (!string.IsNullOrEmpty(Title))
			{
				Console.Error.WriteLine(Title);
				Console.Error.WriteLine();
			}
			if (!string.IsNullOrEmpty(message))
			{
				Console.Error.WriteLine(message, args);
				Console.Error.WriteLine();
			}
			Dictionary<string, MemberInfo> dictionary = _optionalOptions.Concat(_atomicOptions).ToDictionary((KeyValuePair<string, MemberInfo> e) => e.Key, (KeyValuePair<string, MemberInfo> e) => e.Value);
			Console.Error.WriteLine("Usage: {0} {1}{2}", fileNameWithoutExtension, string.Join(" ", _requiredUsageHelp.ToArray()), (dictionary.Count > 0) ? " <Options>" : string.Empty);
			if (dictionary.Count <= 0)
			{
				return;
			}
			Console.Error.WriteLine();
			Console.Error.WriteLine("Options:\n");
			foreach (KeyValuePair<string, MemberInfo> item in dictionary)
			{
				FieldInfo fieldInfo = item.Value as FieldInfo;
				MethodInfo methodInfo = item.Value as MethodInfo;
				CommandLineParameterAttribute attribute = GetAttribute<CommandLineParameterAttribute>(item.Value);
				if ((fieldInfo != null && fieldInfo.FieldType != typeof(bool)) || (methodInfo != null && methodInfo.GetParameters().Length != 0))
				{
					if (string.IsNullOrEmpty(attribute.ShortName))
					{
						Console.Error.WriteLine("  -{0} {1}\n", attribute.ShortName, attribute.ValueName);
					}
					Console.Error.WriteLine("  --{0} {1}\n     {2}\n", attribute.Name, attribute.ValueName, attribute.Description);
				}
				else if (!attribute.Hidden)
				{
					if (string.IsNullOrEmpty(attribute.ShortName))
					{
						Console.Error.WriteLine("  -{0}\n", attribute.ShortName);
					}
					Console.Error.WriteLine("  --{0}\n     {1}\n", attribute.Name, attribute.Description);
				}
			}
		}

		private static T GetAttribute<T>(ICustomAttributeProvider provider) where T : Attribute
		{
			return provider.GetCustomAttributes(typeof(T), inherit: false).OfType<T>().FirstOrDefault();
		}

		public static bool QuickScanParam(string flag, string[] args)
		{
			if (args.Length == 0)
			{
				return false;
			}
			for (int i = 0; i < args.Length; i++)
			{
				if (args[i].Equals(flag))
				{
					return true;
				}
			}
			return false;
		}
	}
	[AttributeUsage(AttributeTargets.Method | AttributeTargets.Field)]
	[Obfuscation(Exclude = true, ApplyToMembers = true)]
	public sealed class CommandLineParameterAttribute : Attribute
	{
		public string Name { get; set; }

		public string ShortName { get; set; }

		public bool RequiredSequential { get; set; }

		public string ValueName { get; set; }

		public string Description { get; set; }

		public bool Atomic { get; set; }

		public bool Hidden { get; set; }

		public CommandLineParameterAttribute()
		{
			ValueName = "value";
		}
	}
	[Serializable]
	public class CrashReport
	{
		public string Application { get; set; }

		public DateTime TimeStamp { get; set; }

		public string Message { get; set; }

		public string DetailedMessage { get; set; }

		public string StackTrace { get; set; }

		public string AssemblyVersion { get; set; }

		public string AssemblyDescription { get; set; }

		public CrashReport()
		{
		}

		public CrashReport(string message, Exception e)
		{
			Application = AssemblyHelper.AssemblyProduct;
			TimeStamp = DateTime.Now;
			Message = message;
			DetailedMessage = e.ToString();
			StackTrace = e.StackTrace;
			AssemblyDescription = AssemblyHelper.AssemblyDescription;
			AssemblyVersion = AssemblyHelper.AssemblyInformationalVersion;
		}

		public override string ToString()
		{
			return string.Format("Fatal Exception in {1} at {2}{0}Message: {3}{0}Detailed: {4}{0}StackTrace: {5}{0}Version: {6}{0}AssemblyInfo: {7}", Environment.NewLine, Application, TimeStamp, Message, DetailedMessage, StackTrace, AssemblyVersion, AssemblyDescription);
		}
	}
	[Obfuscation(Exclude = true, ApplyToMembers = true)]
	internal enum ReturnCode
	{
		Success = 0,
		InvalidCommandLine = 1,
		InvalidXml = 2,
		InvalidOutputPath = 3,
		InvalidImportPath = 4,
		InvalidProject = 5,
		InvalidConfigParameter = 6,
		InvalidOptionsParameter = 7,
		InvalidTaskParameter = 8,
		InvalidAssetDeletion = 9,
		InvalidWarningLevel = 10,
		InvalidPagesDir = 11,
		InvalidProfile = 12,
		InvalidCodingProfile = 13,
		InvalidSoupDir = 14,
		ImportError = 100,
		BuildError = 101,
		ImportErrorInvalidGTexFile = 102,
		MissingDlls = 200,
		InvalidLicense = 300
	}
	internal class Program
	{
		public static CommandLineOptions options = new CommandLineOptions();

		public static Logger logger = new Logger((Verbosity)2);

		public static byte[] GrBuildTag = new byte[64]
		{
			167, 97, 249, 76, 171, 132, 16, 23, 61, 82,
			82, 43, 29, 29, 78, 33, 76, 142, 230, 28,
			142, 225, 149, 164, 56, 9, 69, 233, 13, 214,
			149, 232, 121, 230, 62, 229, 223, 27, 228, 75,
			204, 223, 71, 62, 46, 96, 187, 241, 89, 54,
			62, 122, 135, 254, 153, 146, 0, 128, 163, 249,
			234, 18, 16, 132
		};

		private static int Validate()
		{
			//IL_001d: Unknown result type (might be due to invalid IL or missing references)
			if (options.newProject)
			{
				Console.Error.WriteLine("Validation works on existing projects. Can not validate.");
				return 2;
			}
			new ProjectBuilder().logger.RegisterLogListener((LogListener)(object)logger);
			XMLValidationResult val = ProjectBuilder.ValidateProjectFile(options.projectPath);
			if (!val.get_Valid())
			{
				Console.Error.WriteLine(((object)val).ToString());
				return 2;
			}
			Console.WriteLine("Valid XML project file.");
			return 0;
		}

		public static bool GetVerbosity(string flagstring, out Verbosity verbosity)
		{
			switch (flagstring.ToLowerInvariant()[0])
			{
			case 'q':
				verbosity = (Verbosity)0;
				break;
			case 'n':
				verbosity = (Verbosity)1;
				break;
			case 'd':
				verbosity = (Verbosity)2;
				break;
			default:
				verbosity = (Verbosity)1;
				return false;
			}
			return true;
		}

		private static void RemoveOldLogs()
		{
			//IL_001d: Unknown result type (might be due to invalid IL or missing references)
			//IL_0023: Expected O, but got Unknown
			int num = 100;
			try
			{
				string text = Path.Combine(Paths.GetDirectoryName(Assembly.GetEntryAssembly().Location), "Logs");
				FileScanner val = new FileScanner();
				val.Scan(text, "GrBuild-backup-*.log", false);
				if (val.get_FoundFiles().Count < num)
				{
					return;
				}
				List<FileInfo> list = new List<FileInfo>();
				foreach (string foundFile in val.get_FoundFiles())
				{
					string fileName = Path.GetFileName(foundFile);
					string pattern = "GrBuild-backup-\\d{4}.\\d{2}.\\d{2}-\\d{2}.\\d{2}.\\d{2}.log";
					if (Regex.Match(fileName, pattern).Success)
					{
						FileInfo item = new FileInfo(foundFile);
						list.Add(item);
					}
				}
				List<FileInfo> list2 = list.OrderByDescending((FileInfo o) => o.LastWriteTimeUtc).ToList();
				for (int i = num; i < list2.Count; i++)
				{
					File.Delete(list2[i].FullName);
				}
			}
			catch
			{
			}
		}

		private static void SetupLoggers()
		{
			//IL_0005: Unknown result type (might be due to invalid IL or missing references)
			//IL_000f: Expected O, but got Unknown
			//IL_00ab: Unknown result type (might be due to invalid IL or missing references)
			//IL_00b1: Expected O, but got Unknown
			logger.RegisterLogListener((LogListener)new ConsoleLogListener());
			string text = Path.Combine(Paths.GetDirectoryName(Assembly.GetEntryAssembly().Location), "Logs");
			try
			{
				Paths.CreateDirectory(text);
				string text2 = Path.Combine(text, "GrBuild.log");
				if (File.Exists(text2))
				{
					string arg = new FileInfo(text2).CreationTime.ToString("yyyy.MM.dd-HH.mm.ss");
					string path = $"GrBuild-backup-{arg}.log";
					int num = 1;
					while (File.Exists(Path.Combine(text, path)))
					{
						path = $"GrBuild-backup-{arg}-{num}.log";
						num++;
					}
					string destFileName = Path.Combine(text, path);
					File.Move(text2, destFileName);
				}
				StreamLogListener val = new StreamLogListener(text2);
				val.LogMessage("GrBuild log started", (Verbosity)0);
				logger.RegisterLogListener((LogListener)(object)val);
			}
			catch (Exception)
			{
				string text3 = $"Unable to set up log file. Logging will only be done to console. Make sure the log directory '{text}' is writable to the application";
				logger.LogError(text3);
			}
			RemoveOldLogs();
		}

		private static int Main(string[] args)
		{
			//IL_0033: Unknown result type (might be due to invalid IL or missing references)
			//IL_01f3: Unknown result type (might be due to invalid IL or missing references)
			//IL_01fa: Expected O, but got Unknown
			//IL_0214: Unknown result type (might be due to invalid IL or missing references)
			//IL_021e: Expected O, but got Unknown
			//IL_02eb: Unknown result type (might be due to invalid IL or missing references)
			//IL_0335: Unknown result type (might be due to invalid IL or missing references)
			//IL_0351: Unknown result type (might be due to invalid IL or missing references)
			//IL_0356: Unknown result type (might be due to invalid IL or missing references)
			//IL_0366: Unknown result type (might be due to invalid IL or missing references)
			//IL_036b: Unknown result type (might be due to invalid IL or missing references)
			//IL_036d: Unknown result type (might be due to invalid IL or missing references)
			//IL_03b1: Unknown result type (might be due to invalid IL or missing references)
			//IL_03b6: Unknown result type (might be due to invalid IL or missing references)
			//IL_03b8: Unknown result type (might be due to invalid IL or missing references)
			//IL_03ff: Unknown result type (might be due to invalid IL or missing references)
			//IL_040b: Unknown result type (might be due to invalid IL or missing references)
			//IL_0415: Unknown result type (might be due to invalid IL or missing references)
			//IL_0606: Unknown result type (might be due to invalid IL or missing references)
			//IL_062e: Unknown result type (might be due to invalid IL or missing references)
			//IL_0633: Unknown result type (might be due to invalid IL or missing references)
			//IL_0660: Unknown result type (might be due to invalid IL or missing references)
			//IL_0692: Unknown result type (might be due to invalid IL or missing references)
			//IL_06c8: Expected O, but got Unknown
			//IL_06ff: Unknown result type (might be due to invalid IL or missing references)
			//IL_0701: Unknown result type (might be due to invalid IL or missing references)
			//IL_0704: Invalid comparison between Unknown and I4
			//IL_0729: Unknown result type (might be due to invalid IL or missing references)
			//IL_072e: Unknown result type (might be due to invalid IL or missing references)
			//IL_0734: Unknown result type (might be due to invalid IL or missing references)
			//IL_0736: Unknown result type (might be due to invalid IL or missing references)
			//IL_0741: Unknown result type (might be due to invalid IL or missing references)
			//IL_0743: Unknown result type (might be due to invalid IL or missing references)
			//IL_0745: Unknown result type (might be due to invalid IL or missing references)
			//IL_074e: Unknown result type (might be due to invalid IL or missing references)
			//IL_0765: Expected O, but got Unknown
			//IL_0780: Expected O, but got Unknown
			//IL_079f: Expected O, but got Unknown
			SetupLoggers();
			ReturnCode result = ReturnCode.Success;
			try
			{
				result = ReturnCode.InvalidOptionsParameter;
				bool flag = (Constants.lightmapMode = CommandLineParser.QuickScanParam("-lightmapmode", args));
				result = ReturnCode.MissingDlls;
				if (!GrBuildLibInterface.IsInitialized)
				{
					GrBuildLibInterface.InitializeGrBuild();
				}
				result = ReturnCode.InvalidLicense;
				if (GrBuildLibInterface.get_InitializationInfo().nixelInfo.value2 == 1000 && !flag)
				{
					logger.LogError("Your license does not allow you to run GrBuild. Your license only supports the use of Tile Set Studio. Please upgrade your license in order to run GrBuild.");
					return 300;
				}
				CommandLineParser commandLineParser = new CommandLineParser(options);
				string text = string.Format("GrBuild {0} (project version {1})", new object[2]
				{
					Constants.get_Version().get_BuildVersion(),
					Constants.get_Version().get_ProjectCompatibilityVersion()
				});
				text = (commandLineParser.Title = text + " Copyright (c) 2012-" + DateTime.Now.Year + " Graphine NV");
				if (!commandLineParser.ParseCommandLine(args))
				{
					return 1;
				}
				if (args.Count() == 0)
				{
					commandLineParser.ShowError("");
					return 1;
				}
				if (options.validate)
				{
					return Validate();
				}
				if (options.showHelp)
				{
					commandLineParser.ShowUsage();
					return 0;
				}
				if (options.showVersion)
				{
					Console.WriteLine(string.Format("GrBuild version {0}, project compatibility version {1}, build info: {2}", new object[3]
					{
						Constants.get_Version().get_BuildVersion(),
						Constants.get_Version().get_ProjectCompatibilityVersion(),
						Constants.get_Version().get_BuildInfo()
					}));
					return 0;
				}
				result = ReturnCode.InvalidImportPath;
				if (options.importAssetsPath != null)
				{
					try
					{
						options.importAssetsPath = Path.GetFullPath(options.importAssetsPath);
					}
					catch
					{
						logger.LogError("Invalid input for --importassets (-i): " + options.importAssetsPath);
						return 4;
					}
				}
				Constants.lightmapMode = options.lightmapmode;
				Constants.allowDeprecatedCodingProfiles = flag;
				ProjectBuilder val = new ProjectBuilder();
				val.logger.RegisterLogListener((LogListener)(object)logger);
				val.add_ProjectUpgrading(new ProjectUpgradingEventHandler(projectBuilder_ProjectUpgrading));
				val.HookBuildErrorsOnGlobalLogger();
				val.set_NoFileLogging(options.noLog);
				val.set_NoPatching(options.nopatching);
				val.set_EnableUniformCoding(!options.disableUniformCoding);
				val.set_EnableStrictMode(options.enableStrictMode);
				val.set_ForceUseGTex(options.forceUseGTex);
				val.set_AllowForeignGTex(options.allowForeignGTex);
				val.set_NoGTSBuilding(options.omitGTS);
				val.set_EnableRedirection(!options.noRedirection);
				val.set_EnableSharedMipGeneration(!options.noSharedMipTiles);
				val.set_EnableMipStripping(!options.noMipStripping);
				BuildMode val2 = (BuildMode)(options.buildGTSforGTex ? 1 : 0);
				if (options.setGuid != null && !Guid.TryParse(options.setGuid, out var _))
				{
					logger.LogError("Invalid input for --setguid: string not a GUID, required format: 00000000-0000-0000-0000-000000000000");
					return 7;
				}
				val.set_OverrideGuid(options.setGuid);
				Error val3 = (Error)0;
				result = ReturnCode.InvalidProject;
				val3 = ((!options.newProject) ? val.LoadProject(options.projectPath) : val.NewProject(options.projectPath));
				if ((int)val3 != 0)
				{
					return 5;
				}
				if (val.get_ReadOnly())
				{
					logger.LogWarning("Project is read only. Changes made to the project will not be saved!");
				}
				result = ReturnCode.InvalidProfile;
				if (!string.IsNullOrEmpty(options.profile))
				{
					val3 = val.SetBuildProfile(options.profile);
					if ((int)val3 != 0)
					{
						return 12;
					}
				}
				result = ReturnCode.InvalidCommandLine;
				if (options.verbosity != null)
				{
					if (!GetVerbosity(options.verbosity, out var verbosity))
					{
						logger.LogError("Invalid input for --verbosity (-v)");
						return 1;
					}
					val.SetVerbosity(verbosity);
					logger.SetVerbosity(verbosity);
				}
				result = ReturnCode.InvalidConfigParameter;
				TargetConfiguration val4 = (TargetConfiguration)2;
				if (options.config != null)
				{
					logger.LogWarning("Changing target configuration is deprecated. Falling back to default (Optimized).");
				}
				result = ReturnCode.InvalidOptionsParameter;
				if (options.options != null && !SetExtraOptions(val, options.options))
				{
					return 7;
				}
				result = ReturnCode.InvalidOutputPath;
				if (options.outputPath != null && !val.SetOutputLocation(options.outputPath))
				{
					return 3;
				}
				result = ReturnCode.InvalidPagesDir;
				if (options.pagesDirectory != null && !val.SetPagesDirectory(options.pagesDirectory))
				{
					logger.LogError("Invalid input for --pagesdir (-p): " + options.pagesDirectory);
					return 11;
				}
				result = ReturnCode.InvalidSoupDir;
				if (options.soupDirectory != null && !val.SetSoupOutputDirectory(options.soupDirectory, true))
				{
					logger.LogError("Invalid input for --gtexdir (-g): " + options.soupDirectory);
					return 14;
				}
				result = ReturnCode.InvalidWarningLevel;
				if (options.warningLevel != null)
				{
					uint num = 0u;
					try
					{
						num = uint.Parse(options.warningLevel);
					}
					catch
					{
						logger.LogError("Invalid input for --warninglevel (-w): " + options.warningLevel);
						return 10;
					}
					if (!val.SetWarningLevel(num))
					{
						return 10;
					}
				}
				if (options.importAssetsPath != null)
				{
					result = ReturnCode.InvalidXml;
					XMLValidationResult val5 = ProjectBuilder.ValidateImportXmlFile(options.importAssetsPath);
					if (!val5.get_Valid())
					{
						logger.LogError("Error validating Asset Import XML file \"" + options.importAssetsPath + "\". Detailed error message: " + ((object)val5).ToString());
						return 2;
					}
					val.SetExclusiveImport(options.exclusiveImport);
					result = ReturnCode.ImportError;
					if (!val.AddLayersAndAssetsFromXMLFile(options.importAssetsPath))
					{
						return 100;
					}
				}
				result = ReturnCode.InvalidTaskParameter;
				Task val6 = (Task)0;
				if (options.task != null)
				{
					try
					{
						val6 = (Task)Enum.Parse(typeof(Task), options.task, ignoreCase: true);
					}
					catch
					{
						logger.LogError("Invalid input for --task (-t):" + options.task);
						return 8;
					}
				}
				CleanOperationParameters cleanOperationParameters = default(CleanOperationParameters);
				cleanOperationParameters.intermediates = true;
				cleanOperationParameters.tileSet = options.cleanIncludeTileset;
				cleanOperationParameters.soups = options.cleanIncludeGTex;
				val.SetCleanOperationParameters(cleanOperationParameters);
				result = ReturnCode.InvalidAssetDeletion;
				if (options.assetToDelete != null)
				{
					try
					{
						if (!val.AddAssetsToRemove(options.assetToDelete))
						{
							return 9;
						}
					}
					catch (UnspecifiedException val7)
					{
						UnspecifiedException val8 = val7;
						logger.LogError(((Exception)(object)val8).Message);
						return 9;
					}
					catch (Exception ex)
					{
						logger.LogError(ex.Message);
						return 9;
					}
				}
				Process val9 = (Process)0;
				if ((int)val6 == 3)
				{
					val9 = ((string.IsNullOrEmpty(options.importAssetsPath) && string.IsNullOrEmpty(options.assetToDelete)) ? ((Process)7) : ((Process)1));
				}
				result = ReturnCode.InvalidConfigParameter;
				val.LoadConfiguration(val4);
				result = ReturnCode.BuildError;
				val.Build(val6, val9, val2);
				if ((int)val.get_ProcessResult() != 0)
				{
					return 101;
				}
			}
			catch (UnspecifiedException val10)
			{
				UnspecifiedException val11 = val10;
				logger.LogError(((Exception)(object)val11).Message);
				return (int)result;
			}
			catch (InvalidDllException val12)
			{
				InvalidDllException val13 = val12;
				logger.LogError(((Exception)(object)val13).Message);
				return 200;
			}
			catch (IncompatibleGTexException val14)
			{
				IncompatibleGTexException val15 = val14;
				logger.LogError("Incompatible GTex file, message: '" + ((Exception)(object)val15).Message + "'");
				return 102;
			}
			catch (Exception ex2)
			{
				CrashReport crashReport = new CrashReport(ex2.Message, ex2);
				string text3 = ex2.Message + "\n";
				text3 += "----------------------------------------\n";
				text3 += "An internal runtime exception has occurred. This may be caused by a configuration error or a internal bug. If this issue persists, please send a bug report with the following information to Granite support either via the support platform (http://support.graphinesoftware.com) or by email (support@graphinesoftware.com).\n";
				text3 += "----------------------------------------\n";
				text3 = text3 + "Error details: " + crashReport.ToString() + "\n";
				text3 += "----------------------------------------\n";
				logger.LogError(text3);
				return (int)result;
			}
			finally
			{
				GrBuildLibInterface.ReleaseGrBuild();
			}
			return 0;
		}

		private static void projectBuilder_ProjectUpgrading(object sender, UpgradeInfo info)
		{
			if (info.get_WillUpgradeCodingProfiles2dot7())
			{
				string text = "The project will upgrade to the latest version. Layer compression formats and Stacked Texture's quality profiles could be altered. Please inspect them.";
				logger.LogInfo(text);
			}
		}

		private static bool SetExtraOptions(ProjectBuilder builder, string extra)
		{
			//IL_01a9: Unknown result type (might be due to invalid IL or missing references)
			//IL_0246: Unknown result type (might be due to invalid IL or missing references)
			//IL_024b: Unknown result type (might be due to invalid IL or missing references)
			//IL_024e: Unknown result type (might be due to invalid IL or missing references)
			//IL_0288: Unknown result type (might be due to invalid IL or missing references)
			string[] array = extra.Split(new char[1] { ',' }, StringSplitOptions.RemoveEmptyEntries);
			foreach (string text in array)
			{
				string[] array2 = text.Split(new char[1] { ':' }, StringSplitOptions.RemoveEmptyEntries);
				if (array2.Length != 2)
				{
					logger.LogError("Invalid key/value: " + text);
					return false;
				}
				switch (array2[0].ToLowerInvariant())
				{
				case "tilingmode":
					try
					{
						builder.SetTilingMode((TilingMode)Enum.Parse(typeof(TilingMode), array2[1], ignoreCase: true));
					}
					catch
					{
						logger.LogError("Invalid value for Tiling Mode");
						return false;
					}
					break;
				case "maximumanisotropy":
					try
					{
						uint maximumAnisotropy = uint.Parse(array2[1]);
						builder.SetMaximumAnisotropy(maximumAnisotropy);
					}
					catch
					{
						logger.LogError("Invalid value for Minimum Anisotropy");
						return false;
					}
					break;
				case "pagesize":
					try
					{
						uint pageSize = uint.Parse(array2[1]);
						builder.SetPageSize(pageSize);
					}
					catch
					{
						logger.LogError("Invalid value for PageSize");
						return false;
					}
					break;
				case "pagingstrategy":
					try
					{
						PagingStrategy pagingStrategy = (PagingStrategy)Enum.Parse(typeof(PagingStrategy), array2[1]);
						builder.SetPagingStrategy(pagingStrategy);
					}
					catch
					{
						logger.LogError("Invalid value for PagingStrategy");
						return false;
					}
					break;
				case "targetdisk":
					try
					{
						builder.SetTargetDisk((TargetDisk)Enum.Parse(typeof(TargetDisk), array2[1], ignoreCase: true));
					}
					catch
					{
						logger.LogError("Invalid value for TargetDisk");
						return false;
					}
					break;
				case "tilewidth":
					try
					{
						uint tileWidth = uint.Parse(array2[1]);
						builder.SetTileWidth(tileWidth);
					}
					catch
					{
						logger.LogError("Invalid value for TileWidth");
						return false;
					}
					break;
				case "tileheight":
					try
					{
						uint tileHeight = uint.Parse(array2[1]);
						builder.SetTileHeight(tileHeight);
					}
					catch
					{
						logger.LogError("Invalid value for TileHeight");
						return false;
					}
					break;
				case "blocksize":
					try
					{
						uint blockSize = uint.Parse(array2[1]);
						builder.SetBlockSize(blockSize);
					}
					catch
					{
						logger.LogError("Invalid value for BlockSize");
						return false;
					}
					break;
				default:
					logger.LogError("Option not recognized: " + array2[0]);
					return false;
				}
			}
			return true;
		}
	}
	internal class Sample
	{
		public static void Test()
		{
		}

		public static void OnFatalError(ProjectBuilder source, BuildProcess process, BuildIssue error)
		{
			Console.Error.WriteLine(((object)(BuildProcess)(ref process)).ToString() + ": " + error.ToString());
		}

		public static ErrorAction OnError(ProjectBuilder source, BuildProcess process, BuildIssue error)
		{
			Console.Error.WriteLine(((object)(BuildProcess)(ref process)).ToString() + ": " + error.ToString());
			return (ErrorAction)1;
		}

		public static void OnWarning(ProjectBuilder source, BuildProcess process, BuildIssue error)
		{
			Console.Error.WriteLine(((object)(BuildProcess)(ref process)).ToString() + ": " + error.ToString());
		}

		private static void RegisterErrorCallbacks(ProjectBuilder projectBuilder)
		{
			//IL_000d: Unknown result type (might be due to invalid IL or missing references)
			//IL_0017: Expected O, but got Unknown
			//IL_0024: Unknown result type (might be due to invalid IL or missing references)
			//IL_002e: Expected O, but got Unknown
			//IL_003b: Unknown result type (might be due to invalid IL or missing references)
			//IL_0045: Expected O, but got Unknown
			projectBuilder.get_BuildReportingHandler().add_OnFatalErrorHandler(new OnBuildFatalError(OnFatalError));
			projectBuilder.get_BuildReportingHandler().add_OnErrorHandler(new OnBuildError(OnError));
			projectBuilder.get_BuildReportingHandler().add_OnWarningHandler(new OnBuildWarning(OnWarning));
		}

		public static void GO()
		{
			//IL_0005: Unknown result type (might be due to invalid IL or missing references)
			//IL_000a: Unknown result type (might be due to invalid IL or missing references)
			//IL_0010: Unknown result type (might be due to invalid IL or missing references)
			//IL_001a: Expected O, but got Unknown
			//IL_001a: Unknown result type (might be due to invalid IL or missing references)
			//IL_0020: Expected O, but got Unknown
			//IL_0020: Unknown result type (might be due to invalid IL or missing references)
			//IL_0026: Unknown result type (might be due to invalid IL or missing references)
			//IL_002c: Unknown result type (might be due to invalid IL or missing references)
			//IL_002e: Unknown result type (might be due to invalid IL or missing references)
			//IL_0034: Unknown result type (might be due to invalid IL or missing references)
			//IL_003a: Expected O, but got Unknown
			//IL_003a: Unknown result type (might be due to invalid IL or missing references)
			//IL_0040: Expected O, but got Unknown
			//IL_005e: Unknown result type (might be due to invalid IL or missing references)
			//IL_0064: Expected O, but got Unknown
			//IL_0082: Unknown result type (might be due to invalid IL or missing references)
			//IL_0084: Unknown result type (might be due to invalid IL or missing references)
			//IL_008a: Unknown result type (might be due to invalid IL or missing references)
			//IL_0090: Expected O, but got Unknown
			//IL_009b: Unknown result type (might be due to invalid IL or missing references)
			//IL_00a2: Expected O, but got Unknown
			//IL_00c8: Unknown result type (might be due to invalid IL or missing references)
			//IL_00cf: Expected O, but got Unknown
			//IL_00e3: Unknown result type (might be due to invalid IL or missing references)
			//IL_00eb: Unknown result type (might be due to invalid IL or missing references)
			//IL_00f4: Unknown result type (might be due to invalid IL or missing references)
			//IL_013f: Unknown result type (might be due to invalid IL or missing references)
			//IL_0144: Unknown result type (might be due to invalid IL or missing references)
			//IL_014a: Unknown result type (might be due to invalid IL or missing references)
			//IL_0154: Expected O, but got Unknown
			//IL_0154: Unknown result type (might be due to invalid IL or missing references)
			//IL_015a: Expected O, but got Unknown
			//IL_015a: Unknown result type (might be due to invalid IL or missing references)
			//IL_0160: Unknown result type (might be due to invalid IL or missing references)
			//IL_0166: Unknown result type (might be due to invalid IL or missing references)
			//IL_0168: Unknown result type (might be due to invalid IL or missing references)
			//IL_016e: Unknown result type (might be due to invalid IL or missing references)
			//IL_017c: Unknown result type (might be due to invalid IL or missing references)
			//IL_0183: Expected O, but got Unknown
			//IL_018a: Unknown result type (might be due to invalid IL or missing references)
			//IL_0194: Expected O, but got Unknown
			//IL_01a2: Unknown result type (might be due to invalid IL or missing references)
			//IL_01a8: Unknown result type (might be due to invalid IL or missing references)
			//IL_01ad: Unknown result type (might be due to invalid IL or missing references)
			//IL_01b8: Unknown result type (might be due to invalid IL or missing references)
			//IL_01c3: Unknown result type (might be due to invalid IL or missing references)
			//IL_01ca: Expected O, but got Unknown
			//IL_01eb: Unknown result type (might be due to invalid IL or missing references)
			//IL_01f2: Expected O, but got Unknown
			//IL_0260: Unknown result type (might be due to invalid IL or missing references)
			//IL_0267: Expected O, but got Unknown
			//IL_0285: Unknown result type (might be due to invalid IL or missing references)
			//IL_028c: Expected O, but got Unknown
			//IL_02bf: Unknown result type (might be due to invalid IL or missing references)
			//IL_02c6: Expected O, but got Unknown
			//IL_02d3: Unknown result type (might be due to invalid IL or missing references)
			//IL_02ea: Unknown result type (might be due to invalid IL or missing references)
			//IL_02ef: Unknown result type (might be due to invalid IL or missing references)
			//IL_02f5: Unknown result type (might be due to invalid IL or missing references)
			//IL_02ff: Expected O, but got Unknown
			//IL_02ff: Unknown result type (might be due to invalid IL or missing references)
			//IL_0305: Expected O, but got Unknown
			//IL_0305: Unknown result type (might be due to invalid IL or missing references)
			//IL_030b: Unknown result type (might be due to invalid IL or missing references)
			//IL_0311: Unknown result type (might be due to invalid IL or missing references)
			//IL_0331: Unknown result type (might be due to invalid IL or missing references)
			//IL_0333: Unknown result type (might be due to invalid IL or missing references)
			//IL_0339: Unknown result type (might be due to invalid IL or missing references)
			//IL_0347: Unknown result type (might be due to invalid IL or missing references)
			//IL_034e: Expected O, but got Unknown
			//IL_0355: Unknown result type (might be due to invalid IL or missing references)
			//IL_035f: Expected O, but got Unknown
			//IL_036d: Unknown result type (might be due to invalid IL or missing references)
			//IL_03b9: Unknown result type (might be due to invalid IL or missing references)
			//IL_03be: Unknown result type (might be due to invalid IL or missing references)
			//IL_03c4: Unknown result type (might be due to invalid IL or missing references)
			//IL_03ce: Expected O, but got Unknown
			//IL_03ce: Unknown result type (might be due to invalid IL or missing references)
			//IL_03d4: Expected O, but got Unknown
			//IL_03d4: Unknown result type (might be due to invalid IL or missing references)
			//IL_03da: Unknown result type (might be due to invalid IL or missing references)
			//IL_03e0: Unknown result type (might be due to invalid IL or missing references)
			//IL_03e7: Expected O, but got Unknown
			//IL_03f7: Unknown result type (might be due to invalid IL or missing references)
			//IL_03fe: Expected O, but got Unknown
			//IL_040c: Unknown result type (might be due to invalid IL or missing references)
			//IL_040f: Unknown result type (might be due to invalid IL or missing references)
			//IL_0415: Unknown result type (might be due to invalid IL or missing references)
			//IL_041c: Expected O, but got Unknown
			//IL_0428: Unknown result type (might be due to invalid IL or missing references)
			//IL_042f: Expected O, but got Unknown
			//IL_0477: Unknown result type (might be due to invalid IL or missing references)
			//IL_0480: Unknown result type (might be due to invalid IL or missing references)
			//IL_0482: Unknown result type (might be due to invalid IL or missing references)
			//IL_0488: Unknown result type (might be due to invalid IL or missing references)
			//IL_0496: Unknown result type (might be due to invalid IL or missing references)
			//IL_049b: Unknown result type (might be due to invalid IL or missing references)
			//IL_04a1: Unknown result type (might be due to invalid IL or missing references)
			//IL_04ab: Expected O, but got Unknown
			//IL_04ab: Unknown result type (might be due to invalid IL or missing references)
			//IL_04b1: Expected O, but got Unknown
			//IL_04b1: Unknown result type (might be due to invalid IL or missing references)
			//IL_04b7: Unknown result type (might be due to invalid IL or missing references)
			//IL_04bd: Unknown result type (might be due to invalid IL or missing references)
			//IL_04ce: Unknown result type (might be due to invalid IL or missing references)
			//IL_04d0: Unknown result type (might be due to invalid IL or missing references)
			//IL_04d6: Unknown result type (might be due to invalid IL or missing references)
			//IL_04e4: Unknown result type (might be due to invalid IL or missing references)
			//IL_04eb: Expected O, but got Unknown
			//IL_04f2: Unknown result type (might be due to invalid IL or missing references)
			//IL_04fc: Expected O, but got Unknown
			//IL_050a: Unknown result type (might be due to invalid IL or missing references)
			//IL_05a8: Unknown result type (might be due to invalid IL or missing references)
			//IL_05d9: Unknown result type (might be due to invalid IL or missing references)
			//IL_05de: Unknown result type (might be due to invalid IL or missing references)
			//IL_05e2: Unknown result type (might be due to invalid IL or missing references)
			//IL_05e7: Unknown result type (might be due to invalid IL or missing references)
			//IL_0625: Unknown result type (might be due to invalid IL or missing references)
			//IL_062a: Unknown result type (might be due to invalid IL or missing references)
			//IL_0630: Unknown result type (might be due to invalid IL or missing references)
			//IL_0636: Unknown result type (might be due to invalid IL or missing references)
			//IL_063d: Expected O, but got Unknown
			//IL_063d: Unknown result type (might be due to invalid IL or missing references)
			//IL_0644: Expected O, but got Unknown
			//IL_0666: Unknown result type (might be due to invalid IL or missing references)
			//IL_066d: Expected O, but got Unknown
			//IL_0696: Unknown result type (might be due to invalid IL or missing references)
			//IL_06a5: Unknown result type (might be due to invalid IL or missing references)
			//IL_06ab: Unknown result type (might be due to invalid IL or missing references)
			//IL_06b3: Unknown result type (might be due to invalid IL or missing references)
			//IL_06ba: Expected O, but got Unknown
			//IL_06c6: Unknown result type (might be due to invalid IL or missing references)
			//IL_06cd: Expected O, but got Unknown
			//IL_06f4: Unknown result type (might be due to invalid IL or missing references)
			//IL_06fb: Expected O, but got Unknown
			//IL_0718: Unknown result type (might be due to invalid IL or missing references)
			//IL_0725: Unknown result type (might be due to invalid IL or missing references)
			//IL_072a: Unknown result type (might be due to invalid IL or missing references)
			//IL_0730: Unknown result type (might be due to invalid IL or missing references)
			//IL_073a: Expected O, but got Unknown
			//IL_073a: Unknown result type (might be due to invalid IL or missing references)
			//IL_0740: Expected O, but got Unknown
			//IL_0740: Unknown result type (might be due to invalid IL or missing references)
			//IL_0746: Unknown result type (might be due to invalid IL or missing references)
			//IL_074c: Unknown result type (might be due to invalid IL or missing references)
			//IL_0753: Expected O, but got Unknown
			//IL_0767: Unknown result type (might be due to invalid IL or missing references)
			//IL_076e: Expected O, but got Unknown
			//IL_0795: Unknown result type (might be due to invalid IL or missing references)
			//IL_079e: Unknown result type (might be due to invalid IL or missing references)
			//IL_07a6: Unknown result type (might be due to invalid IL or missing references)
			try
			{
				GrBuildLibInterface.InitializeGrBuild();
				ProjectBuilder val = new ProjectBuilder();
				val.logger.RegisterLogListener((LogListener)new ConsoleLogListener());
				RegisterErrorCallbacks(val);
				val.NewProject("myproject.grproj");
				val.LoadConfiguration((TargetConfiguration)0);
				LayerConfig val2 = new LayerConfig();
				LayerDescription val3 = new LayerDescription();
				val3.set_DataType(DataType.R8G8B8A8_LINEAR);
				val3.set_QualityProfile("Default");
				val2.get_Layers().Add(val3);
				LayerDescription val4 = new LayerDescription();
				val4.set_DataType(DataType.X8Y8Z0_TANGENT);
				val4.set_QualityProfile("Default");
				val2.get_Layers().Add(val4);
				val.SetLayerConfig(val2);
				ImportAsset val5 = new ImportAsset();
				val5.set_Name("MyAsset");
				ImportAssetLayer val6 = new ImportAssetLayer();
				val6.get_Source().AddSource(".\\..\\..\\..\\..\\AcceptanceTestingFramework\\Content\\Random\\tile_metal_grey_dark02_dff.tif", 0);
				val6.set_QualityProfile("High");
				val5.AddAssetLayer(val6);
				ImportAssetLayer val7 = new ImportAssetLayer();
				val7.set_QualityProfile("High");
				val5.AddAssetLayer(val7);
				val.AddImportAsset(val5);
				val.Build((Task)0, (Process)1, (BuildMode)0);
				ImportSummary importSummary = val.GetImportSummary();
				Console.WriteLine("Successful imports: " + importSummary.get_SuccessImportCount());
				Console.WriteLine("Failed imports: " + importSummary.get_FailedImportCount());
				val.CloseProject();
				ProjectBuilder val8 = new ProjectBuilder();
				val8.logger.RegisterLogListener((LogListener)new ConsoleLogListener());
				RegisterErrorCallbacks(val8);
				val8.LoadProject("myproject.grproj");
				val8.LoadConfiguration((TargetConfiguration)2);
				val8.Build((Task)0, (Process)0, (BuildMode)0);
				val8.CloseProject();
				ProjectBuilder val9 = new ProjectBuilder();
				val9.logger.RegisterLogListener((LogListener)new ConsoleLogListener());
				RegisterErrorCallbacks(val9);
				val9.LoadProject("myproject.grproj");
				CodingProfile val10 = new CodingProfile();
				val10.set_Name("MyCustomCodingProfile");
				val10.set_QualityProfiles(new List<QualityProfile>());
				QualityProfile val11 = new QualityProfile();
				val11.set_Name("MyCustomQualityProfile");
				val11.set_Priority(100u);
				val11.set_CodingConfigs(new List<CodingConfig>());
				CodingConfig val12 = new CodingConfig();
				val12.set_DataTypes(new List<DataType>());
				val12.get_DataTypes().Add(DataType.R8G8B8A8_SRGB);
				val12.get_DataTypes().Add(DataType.R8G8B8_SRGB);
				val12.get_DataTypes().Add(DataType.R8G8B8A8_LINEAR);
				val12.get_DataTypes().Add(DataType.R8G8B8_LINEAR);
				val12.set_CodecId(1);
				val12.set_CodecConfiguration("<DefaultQP>1</DefaultQP>");
				val11.get_CodingConfigs().Add(val12);
				val10.get_QualityProfiles().Add(val11);
				ImportAssetLayer val13 = new ImportAssetLayer();
				val13.get_Source().AddSource(".\\..\\..\\..\\..\\AcceptanceTestingFramework\\Content\\Random\\tile_metal_grey_dark02_dff.tif", 0);
				val13.set_QualityProfile("MyCustomQualityProfile");
				ImportAssetLayer val14 = new ImportAssetLayer();
				val14.get_Source().AddSource(".\\..\\..\\..\\..\\AcceptanceTestingFramework\\Content\\Random\\tile_floor_rubber_nrm.tif", 0);
				val14.set_QualityProfile("High");
				ImportAsset val15 = new ImportAsset("MyAsset", (ImportAssetLayer[])(object)new ImportAssetLayer[2] { val13, val14 });
				val9.AddImportAsset(val15);
				val9.LoadConfiguration((TargetConfiguration)2);
				val9.Build((Task)0, (Process)1, (BuildMode)0);
				val9.CloseProject();
				ProjectBuilder val16 = new ProjectBuilder();
				val16.logger.RegisterLogListener((LogListener)new ConsoleLogListener());
				RegisterErrorCallbacks(val16);
				val16.LoadProject("myproject.grproj");
				val16.GetAsset("MyAsset").get_AssetLayers()[0].set_QualityProfile("MyCustomQualityProfile");
				val16.LoadConfiguration((TargetConfiguration)2);
				val16.Build((Task)0, (Process)0, (BuildMode)0);
				val16.CloseProject();
				ProjectBuilder val17 = new ProjectBuilder();
				val17.logger.RegisterLogListener((LogListener)new ConsoleLogListener());
				RegisterErrorCallbacks(val17);
				val17.LoadProject("myproject.grproj");
				List<string> assetNames = val17.GetAssetNames();
				Console.WriteLine("Included assets: ");
				foreach (string item2 in assetNames)
				{
					Console.WriteLine(item2);
				}
				val17.CloseProject();
				ProjectBuilder val18 = new ProjectBuilder();
				val18.logger.RegisterLogListener((LogListener)new ConsoleLogListener());
				RegisterErrorCallbacks(val18);
				val18.NewProject("myproject2.grproj");
				LayerConfig val19 = new LayerConfig();
				LayerDescription item = new LayerDescription(DataType.R8G8B8A8_SRGB, "Default", "Default", "Diffuse");
				val19.get_Layers().Add(item);
				val18.SetLayerConfig(val19);
				ImportAssetTemplate val20 = new ImportAssetTemplate();
				val20.set_Name("Kitten*");
				ImportAssetLayerTemplate val21 = new ImportAssetLayerTemplate();
				val21.get_Source().AddSource(".\\..\\..\\..\\..\\AcceptanceTestingFramework\\Content\\Random\\Kitten_*.jpg", 0);
				val21.set_QualityProfile("high");
				val21.get_Swizzle()[0] = "0123";
				val21.get_InvertChannels()[0] = "0000";
				val20.get_LayerTemplates().Add(val21);
				val18.AddImportAssetsByTemplate(val20);
				val18.LoadConfiguration((TargetConfiguration)2);
				val18.Build((Task)0, (Process)0, (BuildMode)0);
				val18.CloseProject();
				ProjectBuilder val22 = new ProjectBuilder();
				val22.logger.RegisterLogListener((LogListener)new ConsoleLogListener());
				RegisterErrorCallbacks(val22);
				val22.LoadProject("myproject2.grproj");
				val22.GetAsset("Kitten5").set_TilingMethod((AssetTilingMethod)1);
				val22.LoadConfiguration((TargetConfiguration)2);
				val22.Build((Task)0, (Process)0, (BuildMode)0);
				val22.CloseProject();
				ProjectBuilder val23 = new ProjectBuilder();
				val23.logger.RegisterLogListener((LogListener)new ConsoleLogListener());
				RegisterErrorCallbacks(val23);
				val23.LoadProject("myproject2.grproj");
				List<string> assetNames2 = val23.GetAssetNames();
				Console.WriteLine("Imported assets: ");
				foreach (string item3 in assetNames2)
				{
					Console.WriteLine("\t" + item3);
				}
				val23.AddAssetsToRemove(assetNames2[0]);
				val23.AddAssetsToRemove(assetNames2[1]);
				Console.WriteLine("Deleting: " + assetNames2[0] + ", " + assetNames2[1]);
				val23.LoadConfiguration((TargetConfiguration)2);
				val23.Build((Task)0, (Process)0, (BuildMode)0);
				List<TextureChange> textureChanges = val23.GetImportSummary().get_TextureChanges();
				Console.WriteLine("\nTexture changes: ");
				foreach (TextureChange item4 in textureChanges)
				{
					TextureChange current2 = item4;
					TextureChangeType changeType = ((TextureChange)(ref current2)).get_ChangeType();
					Console.WriteLine(((object)(TextureChangeType)(ref changeType)).ToString() + " " + ((TextureChange)(ref current2)).get_Source());
				}
				SolutionBuilder val24 = new SolutionBuilder();
				val24.NewSolution("myproject.grsol");
				LayerConfig val25 = new LayerConfig();
				LayerDescription val26 = new LayerDescription();
				val26.set_DataType(DataType.R8G8B8A8_LINEAR);
				val26.set_QualityProfile("Default");
				val25.get_Layers().Add(val26);
				LayerDescription val27 = new LayerDescription();
				val27.set_DataType(DataType.X8Y8Z0_TANGENT);
				val27.set_QualityProfile("Default");
				val25.get_Layers().Add(val27);
				Guid empty = Guid.Empty;
				val24.CreateNewProject("test", "C:\\Temp\\", val25, ref empty);
				ProjectBuilder projectBuilder = val24.GetProjectBuilder(empty);
				ImportAsset val28 = new ImportAsset();
				val28.set_Name("MyAsset");
				ImportAssetLayer val29 = new ImportAssetLayer();
				val29.get_Source().AddSource(".\\..\\..\\..\\..\\AcceptanceTestingFramework\\Content\\Random\\tile_metal_grey_dark02_dff.tif", 0);
				val29.set_QualityProfile("High");
				val28.AddAssetLayer(val29);
				ImportAssetLayer val30 = new ImportAssetLayer();
				val30.set_QualityProfile("High");
				val28.AddAssetLayer(val30);
				projectBuilder.AddImportAsset(val28);
				val24.LoadConfiguration((TargetConfiguration)2);
				val24.BuildSolution((BuildMode)0);
				ProjectBuilder val31 = new ProjectBuilder();
				val31.logger.RegisterLogListener((LogListener)new ConsoleLogListener());
				RegisterErrorCallbacks(val31);
				val31.LoadProject("myproject.grproj");
				ImportAsset val32 = new ImportAsset();
				val32.set_Name("MyCube");
				val32.set_Type((AssetType)1);
				ImportAssetLayer val33 = new ImportAssetLayer();
				val33.get_Source().AddSource("cube.dds", 0);
				val33.set_QualityProfile("High");
				val32.AddAssetLayer(val33);
				val31.AddImportAsset(val32);
				val31.Import(val32);
				ImportSummary importSummary2 = val31.GetImportSummary();
				Console.WriteLine("Successful imports: " + importSummary2.get_SuccessImportCount());
				Console.WriteLine("Failed imports: " + importSummary2.get_FailedImportCount());
				val31.CloseProject();
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex.Message);
			}
			finally
			{
				GrBuildLibInterface.ReleaseGrBuild();
			}
		}
	}
}
